sudo: false
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
    - npm install

script:
    - npm run build

after_script:
    - cd ./dist
    - git init
    - git config user.name "chengzao"
    - git config user.email "czhlink@163.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
    only:
        - master
env:
    global:
        - GH_REF: github.com/chengzao/guide.git
